GET http://localhost:3000/api/v1/products/01JSDBK7Z11FZ34GCG2E57FDWY


###

POST http://localhost:3000/api/v1/products

{
    "id": "01JSAXA4GS24E1PNKEBJW7NW41",
    "name": "Licensed Aluminum Bacon",
    "price": 537,
    "image": "https://picsum.photos/seed/jsI4D2/3969/1770"
  }

###
PATCH http://localhost:3000/api/v1/products/123
Content-Type: application/json

{
    "id": "01JSD6AD28FZTV7ZR6YTYRJ7KE",
    "price": 894,
    "image": "SinImagen"
  }

###
DELETE http://localhost:3000/api/v1/products/01JSD6P0B1P4BZ11JBMTHSHFTC
Content-Type: application/json


